
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getAnalysisById, archiveAnalysis, exportSingleAnalysis, addPraxisLog } from '../services/storage';
import { Analysis } from '../types';
import { TopBar } from '../components/Navbar';
import { Button } from '../components/Button';
import { Archive, Edit3, Share2, FileText, ShieldAlert, Target, CheckCircle2, Printer, FileDown, FileJson, Plus, Circle } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';

const AnalysisView: React.FC = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { t } = useLanguage();
  const [analysis, setAnalysis] = useState<Analysis | null>(null);
  const [shareFeedback, setShareFeedback] = useState(false);
  
  // Praxis Log State
  const [logInput, setLogInput] = useState('');

  useEffect(() => {
    if (id) {
      const data = getAnalysisById(id);
      if (data) setAnalysis(data);
    }
  }, [id]);

  const refreshData = () => {
      if (id) {
          const data = getAnalysisById(id);
          if (data) setAnalysis(data);
      }
  };

  if (!analysis) return null;

  const getCategoryLabel = (qId: string) => t.questions[qId]?.categoryLabel || qId;

  const handleArchive = () => {
      if (window.confirm(t.view.confirmArchive)) {
          archiveAnalysis(analysis.id);
          navigate('/');
      }
  };

  const handlePrint = () => {
      window.print();
  };

  const handleExportJSON = () => {
      exportSingleAnalysis(analysis.id);
  };

  const handleExportMarkdown = () => {
      const date = new Date(analysis.createdAt).toLocaleDateString();
      const tags = analysis.tags ? analysis.tags.join(', ') : '';
      
      let praxisSection = '';
      if (analysis.praxisLog && analysis.praxisLog.length > 0) {
          praxisSection = `\n## 6. Praxis Log\n` + 
              analysis.praxisLog.map(l => `- [${new Date(l.timestamp).toLocaleDateString()}] ${l.text}`).join('\n');
      }

      const content = `
# ${analysis.title}
**Date:** ${date}
**Ref:** ${analysis.id}
**Tags:** ${tags}

---

## 1. ${t.view.objectLabel}
${analysis.thesis}

## 2. ${t.view.contradictionLabel}
> "${analysis.synthesis}"

## 3. ${t.view.modulesTitle}
${analysis.answers.map(a => `- **${getCategoryLabel(a.questionId)}:** ${a.text}`).join('\n')}

## 4. ${t.view.strategyTitle}
### ${t.wizard.vulnLabel}
${analysis.vulnerabilities}

### ${t.wizard.oppLabel}
${analysis.opportunities}

## 5. ${t.view.risksTitle}
${analysis.risks}

${praxisSection}

---
*Generated by Meth0d Protocol*
      `.trim();

      const blob = new Blob([content], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${analysis.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
     const text = `PROTOCOL: ${analysis.title}\nTHESIS: ${analysis.thesis}\n\nCONTRADICTION: ${analysis.synthesis}\n\nVULNERABILITIES: ${analysis.vulnerabilities}\nOPPORTUNITIES: ${analysis.opportunities}\nRISKS: ${analysis.risks}\n\nGenerated by Meth0d.`;
     
     const copyToClipboard = async () => {
        try {
             await navigator.clipboard.writeText(text);
             setShareFeedback(true);
             setTimeout(() => setShareFeedback(false), 3000);
         } catch (clipboardError) {
             alert("Failed to copy to clipboard.");
         }
     };

     if (navigator.share) {
         try {
             await navigator.share({
                 title: analysis.title,
                 text: text,
             });
         } catch (error) {
             console.log("Share skipped, trying clipboard", error);
             await copyToClipboard();
         }
     } else {
         await copyToClipboard();
     }
  };

  const handleAddLog = () => {
      if (!logInput.trim()) return;
      addPraxisLog(analysis.id, logInput);
      setLogInput('');
      refreshData();
  };

  return (
    <>
      <style>{`
          @media print {
            .no-print, nav, header { display: none !important; }
            body { background: white !important; color: black !important; }
            .text-text-inverted { color: black !important; }
            .bg-secondary, .bg-surface, .bg-surface-highlight, .bg-danger\\/5, .bg-success\\/5 { 
                background: white !important; 
                border: 1px solid #ccc !important;
                box-shadow: none !important;
                color: black !important;
            }
            * { font-family: 'Times New Roman', serif !important; }
            .print-header { display: block !important; margin-bottom: 20px; border-bottom: 2px solid black; padding-bottom: 10px; }
            .print-hidden { display: none !important; }
            .print-grid { display: grid !important; grid-template-columns: 1fr 1fr !important; gap: 20px !important; }
          }
          .print-header { display: none; }
      `}</style>

      <TopBar title={t.view.briefingTitle} showBack />
      
      <div className="max-w-2xl mx-auto p-4 space-y-6 animate-fade-in pb-24 print:p-0 print:max-w-none">
        
        {/* Print Only Header */}
        <div className="print-header">
            <h1 className="text-2xl font-bold uppercase">Strategic Briefing</h1>
            <p className="text-sm">Generated by Meth0d Protocol</p>
        </div>

        <div className="flex justify-between items-center mb-2">
            <div className="flex flex-col">
                <span className="bg-secondary text-text-inverted text-xs font-mono px-2 py-1 rounded inline-block w-max mb-1">
                    REF: {analysis.id.slice(0,8).toUpperCase()}
                </span>
                {analysis.tags && analysis.tags.length > 0 && (
                    <div className="flex gap-1">
                        {analysis.tags.map(tag => (
                            <span key={tag} className="text-[10px] text-text-muted border border-surface-highlight px-1 rounded">
                                {tag}
                            </span>
                        ))}
                    </div>
                )}
            </div>
            <span className="text-xs text-text-muted font-mono">
                {new Date(analysis.createdAt).toLocaleDateString()}
            </span>
        </div>

        {/* OBJECT */}
        <section className="bg-surface rounded-lg p-4 border-l-4 border-text-muted shadow-sm">
            <h3 className="text-xs font-bold text-text-muted uppercase tracking-wider mb-2">{t.view.objectLabel}</h3>
            <p className="text-text-main font-medium">{analysis.title}</p>
            <p className="text-sm text-text-muted mt-1 italic">{analysis.thesis}</p>
        </section>

        {/* CENTRAL CONTRADICTION */}
        <section className="bg-secondary text-text-inverted rounded-xl p-6 shadow-lg ring-4 ring-primary/10 relative overflow-hidden">
            <div className="absolute top-0 right-0 -mt-4 -mr-4 w-24 h-24 bg-primary opacity-20 rounded-full blur-xl no-print"></div>
            <h3 className="text-xs font-bold text-text-inverted/70 uppercase tracking-wider mb-3 flex items-center">
                 <FileText size={14} className="mr-2"/> {t.view.contradictionLabel}
            </h3>
            <p className="text-xl font-serif font-medium leading-relaxed">"{analysis.synthesis}"</p>
        </section>

        {/* STRATEGY SECTION */}
        <div className="grid gap-4 md:grid-cols-2 print-grid">
             {/* Vulnerabilities */}
            <div className="bg-danger/5 rounded-lg p-4 border border-danger/20">
                <h4 className="text-xs font-bold text-danger uppercase mb-2 flex items-center">
                    <Target size={14} className="mr-1"/> {t.wizard.vulnLabel}
                </h4>
                <p className="text-sm text-text-main whitespace-pre-line">{analysis.vulnerabilities || "N/A"}</p>
            </div>

            {/* Opportunities */}
            <div className="bg-success/5 rounded-lg p-4 border border-success/20">
                <h4 className="text-xs font-bold text-success uppercase mb-2 flex items-center">
                    <Target size={14} className="mr-1"/> {t.wizard.oppLabel}
                </h4>
                <p className="text-sm text-text-main whitespace-pre-line">{analysis.opportunities || "N/A"}</p>
            </div>
        </div>

        {/* RISKS */}
        {analysis.risks && (
            <section className="bg-surface-highlight rounded-lg p-4 border-l-4 border-warning">
                 <h3 className="text-xs font-bold text-warning uppercase tracking-wider mb-2 flex items-center">
                    <ShieldAlert size={14} className="mr-2"/> {t.view.risksTitle}
                 </h3>
                 <p className="text-sm text-text-muted whitespace-pre-line">{analysis.risks}</p>
            </section>
        )}

        {/* PRAXIS LOG SECTION */}
        <section className="mt-8 border-t border-surface-highlight pt-6 no-print">
            <h3 className="text-xs font-bold text-text-muted uppercase mb-4 tracking-wider flex items-center">
                <CheckCircle2 size={14} className="mr-2" /> {t.view.praxisTitle}
            </h3>

            {/* Log Input */}
            <div className="bg-surface rounded-lg p-3 border border-surface-highlight mb-6 shadow-sm focus-within:ring-2 focus-within:ring-primary/20 transition-all">
                <textarea 
                    className="w-full bg-transparent outline-none text-sm text-text-main resize-none placeholder-text-muted/50"
                    rows={2}
                    placeholder={t.view.praxisPlaceholder}
                    value={logInput}
                    onChange={(e) => setLogInput(e.target.value)}
                    onKeyDown={(e) => {
                        if (e.key === 'Enter' && !e.shiftKey) {
                            e.preventDefault();
                            handleAddLog();
                        }
                    }}
                />
                <div className="flex justify-end mt-2">
                    <button 
                        onClick={handleAddLog}
                        disabled={!logInput.trim()}
                        className="text-xs bg-primary text-text-inverted px-3 py-1.5 rounded font-bold hover:bg-primary/90 disabled:opacity-50 transition-colors flex items-center"
                    >
                        <Plus size={12} className="mr-1"/> {t.view.btnAddLog}
                    </button>
                </div>
            </div>

            {/* Log Timeline */}
            <div className="relative border-l-2 border-surface-highlight ml-3 pl-6 space-y-6">
                {(!analysis.praxisLog || analysis.praxisLog.length === 0) ? (
                    <div className="text-sm text-text-muted opacity-50 italic">
                        No entries yet.
                    </div>
                ) : (
                    analysis.praxisLog.map((log) => (
                        <div key={log.id} className="relative animate-fade-in">
                            <div className="absolute -left-[31px] top-1 bg-surface rounded-full p-1 border border-surface-highlight text-primary">
                                <Circle size={8} fill="currentColor" />
                            </div>
                            <div className="text-[10px] font-mono text-text-muted mb-1">
                                {new Date(log.timestamp).toLocaleString()}
                            </div>
                            <div className="bg-surface p-3 rounded-lg border border-surface-highlight shadow-sm text-sm text-text-main whitespace-pre-wrap">
                                {log.text}
                            </div>
                        </div>
                    ))
                )}
            </div>
        </section>

        {/* MODULE DATA - QUADRANT GRID VIEW */}
        <div className="mt-8 pt-8 border-t border-surface-highlight">
            <h3 className="text-xs font-bold text-text-muted uppercase px-2 mb-2">{t.view.modulesTitle}</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 print-grid">
                {analysis.answers.map((ans, idx) => (
                    <div key={idx} className="bg-surface rounded-lg px-4 py-4 border border-surface-highlight shadow-sm h-full">
                        <p className="text-[10px] text-primary font-bold uppercase mb-2 border-b border-surface-highlight pb-1">
                            {getCategoryLabel(ans.questionId)}
                        </p>
                        <p className="text-sm text-text-main leading-relaxed">{ans.text}</p>
                    </div>
                ))}
            </div>
        </div>

        <div className="grid grid-cols-2 gap-4 pt-4 no-print">
            <Button variant="secondary" onClick={() => navigate(`/edit/${analysis.id}`)}>
                <Edit3 size={18} className="mr-2" /> {t.view.btnEdit}
            </Button>
            
            <Button variant="outline" onClick={handleExportMarkdown}>
                <FileDown size={18} className="mr-2" /> {t.view.btnExportMD}
            </Button>

            <Button variant="outline" onClick={handleExportJSON}>
                <FileJson size={18} className="mr-2" /> {t.view.btnExportJSON}
            </Button>

            <Button variant="outline" onClick={handlePrint} className="">
                <Printer size={18} className="mr-2" /> {t.view.btnPrint}
            </Button>

            <Button variant={shareFeedback ? "success" : "outline"} onClick={handleShare} className="col-span-2">
                {shareFeedback ? (
                    <><CheckCircle2 size={18} className="mr-2" /> {t.view.shareSuccess}</>
                ) : (
                    <><Share2 size={18} className="mr-2" /> {t.view.btnShare}</>
                )}
            </Button>
            
            <Button variant="ghost" className="col-span-2 text-danger hover:bg-danger/10" onClick={handleArchive}>
                <Archive size={18} className="mr-2" /> {t.view.btnArchive}
            </Button>
        </div>
      </div>
    </>
  );
};

export default AnalysisView;